services:
  - type: web
    name: the-75-project-api
    env: docker
    rootDir: backend
    plan: free
    envVars:
      - key: NIM_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: EXPO_PUBLIC_SUPABASE_URL
        sync: false
      - key: EXPO_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
